### ISSUE TITLE
Way to configure the command is not very clear

### ISSUE THREAD

**Issue by fritz-smh** [vdomos/domogik-plugin-script#1]
Hi,

I wanted to create such a command : "time > /tmp/dmgscr"

I badly put all in the "program" field and nothing in the arg one.

Can't we do an upgrade to use only 1 field parameter for the whole command line

For information, the error i got :

```
2015-12-10 11:31:09,811 domogik-script DEBUG ### Call script_cmnd_cb                                                    
2015-12-10 11:31:09,811 domogik-script INFO ### Run program 'time > /tmp/dmgscr' type 'cmd_action' with parameters 'none
'                                                                                                                       
2015-12-10 11:31:09,811 domogik-script INFO ### Execute subprocess '['time > /tmp/dmgscr']'                             
2015-12-10 11:31:09,826 domogik-script ERROR ### Command '['time > /tmp/dmgscr']' failed with OSerror : 2, (No such file
 or directory)                                                                                                
```

**Comment by vdomos** [comment]
Hi,
I made some corrections.
it is now possible to write the command with parameter in the first fields and ignored the "arg" fields or not, I delete it later.

For security reasons, it is not possible to use character '>' <'or' | 'in a script (subprocess.check_output with "shell = False").
And I think it's better this way.

**Comment by fritz-smh** [comment]
Ok pour >< but you shloud tell about this limitation in the field description. I used this only to test by logging in a file ;)

**Comment by vdomos** [comment]
ok, I will add this precision in the description and documentation.

Regarding the use of two parameters "field" and "arg"  is the consequence of the xPL message exec.basic:

```
EXEC.BASIC
{
pid=[anything you like - this is just sent back unchanged in the status messages]
program=[executable filename, including extension, but without path]
arg=[optional command line argument]
arg=[next argument]
arg=[etc]
}
```

**Comment by fritz-smh** [comment]
honestly, don't be too strict with xpl ;)

**Comment by vdomos** [comment]
Hi,
I followed your advice and improve my plugin.
I was inspired by the ping plugin to manage the sensor script.More simple to use.

It is available on the Develop branch.
The documenatation that goes with it: http://domogik-plugin-script.readthedocs.org/en/develop/index.html

**Comment by fritz-smh** [comment]
it seems ok for me. Closing
