### ISSUE TITLE
Add informations in the logs about OsError 8

### ISSUE THREAD

**Issue by fritz-smh** [vdomos/domogik-plugin-script#3]
The case : 

```
2015-12-31 12:01:59,517 domogik-script INFO ==> Execute subprocess for '['/tmp/test.sh']'
2015-12-31 12:01:59,531 domogik-script ERROR ### Script '/tmp/test.sh' failed with OSerror : 8,      (Exec format error)
```

The script : 

```
$ cat /tmp/test.sh 
echo " BOOOM "
```

The error is : OSError: [Errno 8] Exec format error can happen if there is no shebang line at the top of the shell script and you are trying to execute the script directly. 

Could you add a specific check on OsError 8 and add this description in this case in the logs to be clearer for the user to debug ?

Thanks,

**Comment by vdomos** [comment]
Add some log to be more comprehensible and some error example in the doc.

**Comment by vdomos** [comment]
A check is made for this case and a specific message is display in log.
Add information in documentation for that too.
