### ISSUE TITLE
100% cpu usage on develop

### ISSUE THREAD

**Issue by tikismoke** [vdomos/domogik-plugin-script#6]
Je sais vraiment pas pourquoi mais si je mets la branch develop au lieu de la 0.2 mon cpu monte à 100% d'utilisation sur ce plugin.

**Comment by vdomos** [comment]
La différence entre la 2.0 et la branch develop c'est qu'il n'y a qu'un seul thread pour tous les scripts Info. C'est le parametre interval qui est comparé pour lancer le script comme pour onewired fait par Nico0084.

Tu aurais un intervall particulier ?

Tu n'aurais rien dans les logs ou des log qui se remplissent tres vite ?

**Comment by tikismoke** [comment]
Rien dans les logs, Je n'ai que des script Action, aucun sensor.

**Comment by vdomos** [comment]
ah c'est peut être la cause, le thread sensor doit tourner à vide, doit avoir une boullette.

tu pourrais me donner ta log en le faisant ttourner quelques minutes

**Comment by tikismoke** [comment]
Non y a absolument rien qui défile dans les logs. Je te les envoie tout à l'heure.

Le 3 mars 2017 17:33:28 GMT+01:00, vdomos <notifications@github.com> a écrit :
>La différence entre la 2.0 et la branch develop c'est qu'il n'y a qu'un
>seul thread pour tous les scripts Info. C'est le parametre interval qui
>est comparé pour lancer le script comme pour onewired fait par
>Nico0084.
>un intervall particulier ?
>
>Tu n'aurais rien dans les logs ou des log qui se remplissent tres vite
>?
>
>
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vdomos/domogik-plugin-script/issues/6#issuecomment-284002072

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by vdomos** [comment]
j'ai pushé une correction, tu pourras tester

**Comment by tikismoke** [comment]
Ok

Le 3 mars 2017 17:55:07 GMT+01:00, vdomos <notifications@github.com> a écrit :
>j'ai pushé une correction, tu pourras tester
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vdomos/domogik-plugin-script/issues/6#issuecomment-284008077

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tikismoke** [comment]
solved with your commit 👍
